swagger: "2.0"
info:
  version: "1.0.0"
  title: vnng-rest
host: localhost:3000
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /ping:
    get:
      description: Test REST server
      responses:
        "200":
          description: Success
  /swagger:
    x-swagger-pipe: swagger_raw